
#include <assert.h>

#include <node_api.h>
#include <SDL2/SDL.h>

#include "./lib/init.h"
#include "./lib/error.h"
#include "./lib/video.h"
#include "./lib/platform.h"
#include "./lib/cpuinfo.h"
#include "./lib/endian.h"
#include "./lib/bits.h"
#include "./lib/power.h"


#ifndef EXPORT_VALUE

  #define EXPORT_VALUE(targ, id, val)                             \
                                                                  \
    do {                                                          \
      napi_status status;                                         \
      napi_value napi_val;                                        \
                                                                  \
      status = napi_create_int32(env, val, &napi_val);            \
      assert(status == napi_ok);                                  \
                                                                  \
      status = napi_set_named_property(env, targ, id, napi_val);  \
      assert(status == napi_ok);                                  \
    } while (0)

#endif

#ifndef EXPORT_METHOD

  #define EXPORT_METHOD(targ, id, meth)                                   \
                                                                          \
    do {                                                                  \
      napi_status status;                                                 \
      napi_value napi_val;                                                \
                                                                          \
      status = napi_create_function(env, NULL, 0, meth, NULL, &napi_val); \
      assert(status == napi_ok);                                          \
                                                                          \
      status = napi_set_named_property(env, targ, id, napi_val);          \
      assert(status == napi_ok);                                          \
    } while (0)

#endif


napi_value Export(napi_env env, napi_value exports) {


  // Init Category
  EXPORT_VALUE(exports, "SDL_INIT_TIMER", SDL_INIT_TIMER);
  EXPORT_VALUE(exports, "SDL_INIT_AUDIO", SDL_INIT_AUDIO);
  EXPORT_VALUE(exports, "SDL_INIT_VIDEO", SDL_INIT_VIDEO);
  EXPORT_VALUE(exports, "SDL_INIT_JOYSTICK", SDL_INIT_JOYSTICK);
  EXPORT_VALUE(exports, "SDL_INIT_HAPTIC", SDL_INIT_HAPTIC);
  EXPORT_VALUE(exports, "SDL_INIT_GAMECONTROLLER", SDL_INIT_GAMECONTROLLER);
  EXPORT_VALUE(exports, "SDL_INIT_EVENTS", SDL_INIT_EVENTS);
  EXPORT_VALUE(exports, "SDL_INIT_EVERYTHING", SDL_INIT_EVERYTHING);
  EXPORT_VALUE(exports, "SDL_INIT_NOPARACHUTE", SDL_INIT_NOPARACHUTE);

  EXPORT_METHOD(exports, "SDL_Init", NAPI_SDL_Init);
  EXPORT_METHOD(exports, "SDL_InitSubSystem", NAPI_SDL_Init);
  EXPORT_METHOD(exports, "SDL_Quit", NAPI_SDL_Quit);
  EXPORT_METHOD(exports, "SDL_QuitSubSystem", NAPI_SDL_QuitSubSystem);
  //EXPORT_METHOD(exports, "SDL_SetMainReady", NAPI_SDL_SetMainReady);
  EXPORT_METHOD(exports, "SDL_WasInit", NAPI_SDL_WasInit);
  //EXPORT_METHOD(exports, "SDL_WinRTRunApp", NAPI_SDL_WinRTRunApp);


  // Configuration Category
  EXPORT_VALUE(exports, "SDL_HINT_ACCELEROMETER_AS_JOYSTICK", SDL_HINT_ACCELEROMETER_AS_JOYSTICK);
  EXPORT_VALUE(exports, "SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION", SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION);
  EXPORT_VALUE(exports, "SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION", SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION);
  //EXPORT_VALUE(exports, "SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH", SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH);
  EXPORT_VALUE(exports, "SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS", SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS);
  EXPORT_VALUE(exports, "SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION", SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION);
  EXPORT_VALUE(exports, "SDL_HINT_BMP_SAVE_LEGACY_FORMAT", SDL_HINT_BMP_SAVE_LEGACY_FORMAT);
  //EXPORT_VALUE(exports, "SDL_HINT_EMSCRIPTEN_ASYNCIFY", SDL_HINT_EMSCRIPTEN_ASYNCIFY);
  EXPORT_VALUE(exports, "SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT", SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT);
  EXPORT_VALUE(exports, "SDL_HINT_FRAMEBUFFER_ACCELERATION", SDL_HINT_FRAMEBUFFER_ACCELERATION);
  EXPORT_VALUE(exports, "SDL_HINT_GAMECONTROLLERCONFIG", SDL_HINT_GAMECONTROLLERCONFIG);
  EXPORT_VALUE(exports, "SDL_HINT_GRAB_KEYBOARD", SDL_HINT_GRAB_KEYBOARD);
  EXPORT_VALUE(exports, "SDL_HINT_IDLE_TIMER_DISABLED", SDL_HINT_IDLE_TIMER_DISABLED);
  EXPORT_VALUE(exports, "SDL_HINT_IME_INTERNAL_EDITING", SDL_HINT_IME_INTERNAL_EDITING);
  EXPORT_VALUE(exports, "SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS", SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS);
  EXPORT_VALUE(exports, "SDL_HINT_MAC_BACKGROUND_APP", SDL_HINT_MAC_BACKGROUND_APP);
  EXPORT_VALUE(exports, "SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK", SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK);
  EXPORT_VALUE(exports, "SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH", SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH);
  EXPORT_VALUE(exports, "SDL_HINT_MOUSE_RELATIVE_MODE_WARP", SDL_HINT_MOUSE_RELATIVE_MODE_WARP);
  EXPORT_VALUE(exports, "SDL_HINT_NO_SIGNAL_HANDLERS", SDL_HINT_NO_SIGNAL_HANDLERS);
  EXPORT_VALUE(exports, "SDL_HINT_ORIENTATIONS", SDL_HINT_ORIENTATIONS);
  EXPORT_VALUE(exports, "SDL_HINT_RENDER_DIRECT3D11_DEBUG", SDL_HINT_RENDER_DIRECT3D11_DEBUG);
  EXPORT_VALUE(exports, "SDL_HINT_RENDER_DIRECT3D_THREADSAFE", SDL_HINT_RENDER_DIRECT3D_THREADSAFE);
  EXPORT_VALUE(exports, "SDL_HINT_RENDER_DRIVER", SDL_HINT_RENDER_DRIVER);
  EXPORT_VALUE(exports, "SDL_HINT_RENDER_OPENGL_SHADERS", SDL_HINT_RENDER_OPENGL_SHADERS);
  EXPORT_VALUE(exports, "SDL_HINT_RENDER_SCALE_QUALITY", SDL_HINT_RENDER_SCALE_QUALITY);
  EXPORT_VALUE(exports, "SDL_HINT_RENDER_VSYNC", SDL_HINT_RENDER_VSYNC);
  EXPORT_VALUE(exports, "SDL_HINT_RPI_VIDEO_LAYER", SDL_HINT_RPI_VIDEO_LAYER);
  EXPORT_VALUE(exports, "SDL_HINT_THREAD_STACK_SIZE", SDL_HINT_THREAD_STACK_SIZE);
  EXPORT_VALUE(exports, "SDL_HINT_TIMER_RESOLUTION", SDL_HINT_TIMER_RESOLUTION);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_ALLOW_SCREENSAVER", SDL_HINT_VIDEO_ALLOW_SCREENSAVER);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_HIGHDPI_DISABLED", SDL_HINT_VIDEO_HIGHDPI_DISABLED);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES", SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS", SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_WIN_D3DCOMPILER", SDL_HINT_VIDEO_WIN_D3DCOMPILER);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT", SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_X11_NET_WM_PING", SDL_HINT_VIDEO_X11_NET_WM_PING);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_X11_XINERAMA", SDL_HINT_VIDEO_X11_XINERAMA);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_X11_XRANDR", SDL_HINT_VIDEO_X11_XRANDR);
  EXPORT_VALUE(exports, "SDL_HINT_VIDEO_X11_XVIDMODE", SDL_HINT_VIDEO_X11_XVIDMODE);
  EXPORT_VALUE(exports, "SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN", SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN);
  EXPORT_VALUE(exports, "SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING", SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING);
  EXPORT_VALUE(exports, "SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP", SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP);
  EXPORT_VALUE(exports, "SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4", SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4);
  EXPORT_VALUE(exports, "SDL_HINT_WINRT_HANDLE_BACK_BUTTON", SDL_HINT_WINRT_HANDLE_BACK_BUTTON);
  EXPORT_VALUE(exports, "SDL_HINT_WINRT_PRIVACY_POLICY_LABEL", SDL_HINT_WINRT_PRIVACY_POLICY_LABEL);
  EXPORT_VALUE(exports, "SDL_HINT_WINRT_PRIVACY_POLICY_URL", SDL_HINT_WINRT_PRIVACY_POLICY_URL);
  EXPORT_VALUE(exports, "SDL_HINT_XINPUT_ENABLED", SDL_HINT_XINPUT_ENABLED);
  EXPORT_VALUE(exports, "SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING", SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING);


  // Error Category
  EXPORT_METHOD(exports, "SDL_ClearError", NAPI_SDL_ClearError);
  EXPORT_METHOD(exports, "SDL_GetError", NAPI_SDL_GetError);
  EXPORT_METHOD(exports, "SDL_SetError", NAPI_SDL_SetError);


  // Log Category
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_APPLICATION", SDL_LOG_CATEGORY_APPLICATION);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_ERROR", SDL_LOG_CATEGORY_ERROR);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_ASSERT", SDL_LOG_CATEGORY_ASSERT);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_SYSTEM", SDL_LOG_CATEGORY_SYSTEM);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_AUDIO", SDL_LOG_CATEGORY_AUDIO);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_VIDEO", SDL_LOG_CATEGORY_VIDEO);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_RENDER", SDL_LOG_CATEGORY_RENDER);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_INPUT", SDL_LOG_CATEGORY_INPUT);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_TEST", SDL_LOG_CATEGORY_TEST);
  //EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_RESERVED", SDL_LOG_CATEGORY_RESERVED);
  EXPORT_VALUE(exports, "SDL_LOG_CATEGORY_CUSTOM", SDL_LOG_CATEGORY_CUSTOM);

  EXPORT_VALUE(exports, "SDL_LOG_PRIORITY_VERBOSE", SDL_LOG_PRIORITY_VERBOSE);
  EXPORT_VALUE(exports, "SDL_LOG_PRIORITY_DEBUG", SDL_LOG_PRIORITY_DEBUG);
  EXPORT_VALUE(exports, "SDL_LOG_PRIORITY_INFO", SDL_LOG_PRIORITY_INFO);
  EXPORT_VALUE(exports, "SDL_LOG_PRIORITY_WARN", SDL_LOG_PRIORITY_WARN);
  EXPORT_VALUE(exports, "SDL_LOG_PRIORITY_ERROR", SDL_LOG_PRIORITY_ERROR);
  EXPORT_VALUE(exports, "SDL_LOG_PRIORITY_CRITICAL", SDL_LOG_PRIORITY_CRITICAL);
  EXPORT_VALUE(exports, "SDL_NUM_LOG_PRIORITIES", SDL_NUM_LOG_PRIORITIES);


  // Assertion Category
  EXPORT_VALUE(exports, "SDL_ASSERTION_RETRY", SDL_ASSERTION_RETRY);
  EXPORT_VALUE(exports, "SDL_ASSERTION_BREAK", SDL_ASSERTION_BREAK);
  EXPORT_VALUE(exports, "SDL_ASSERTION_ABORT", SDL_ASSERTION_ABORT);
  EXPORT_VALUE(exports, "SDL_ASSERTION_IGNORE", SDL_ASSERTION_IGNORE);
  EXPORT_VALUE(exports, "SDL_ASSERTION_ALWAYS_IGNORE", SDL_ASSERTION_ALWAYS_IGNORE);


  // Version Query Category
  EXPORT_VALUE(exports, "SDL_COMPILEDVERSION", SDL_COMPILEDVERSION);
  //EXPORT_VALUE(exports, "SDL_REVISION", SDL_REVISION);
  //EXPORT_VALUE(exports, "SDL_VERSION", SDL_VERSION);
  //EXPORT_VALUE(exports, "SDL_VERSION_ATLEAST", SDL_VERSION_ATLEAST);
  //EXPORT_VALUE(exports, "SDL_VERSIONNUL", SDL_VERSIONNUM);


  // Display and Window Management Category
  EXPORT_METHOD(exports, "SDL_CreateWindow", NAPI_SDL_CreateWindow);

  // Platform Category
  EXPORT_METHOD(exports, "SDL_GetPlatform", NAPI_SDL_GetPlatform);
  EXPORT_METHOD(exports, "SDL_GetCPUCacheLineSize", NAPI_SDL_GetCPUCacheLineSize);
  EXPORT_METHOD(exports, "SDL_GetCPUCount", NAPI_SDL_GetCPUCount);
  EXPORT_METHOD(exports, "SDL_GetSystemRAM", NAPI_SDL_GetSystemRAM);

  EXPORT_METHOD(exports, "SDL_Has3DNow", NAPI_SDL_Has3DNow);
  EXPORT_METHOD(exports, "SDL_HasAltiVec", NAPI_SDL_HasAltiVec);
  EXPORT_METHOD(exports, "SDL_HasAVX", NAPI_SDL_HasAVX);
  EXPORT_METHOD(exports, "SDL_HasAVX2", NAPI_SDL_HasAVX2);
  EXPORT_METHOD(exports, "SDL_HasMMX", NAPI_SDL_HasMMX);
  EXPORT_METHOD(exports, "SDL_HasRDTSC", NAPI_SDL_HasRDTSC);
  EXPORT_METHOD(exports, "SDL_HasSSE", NAPI_SDL_HasSSE);
  EXPORT_METHOD(exports, "SDL_HasSSE2", NAPI_SDL_HasSSE2);
  EXPORT_METHOD(exports, "SDL_HasSSE3", NAPI_SDL_HasSSE3);
  EXPORT_METHOD(exports, "SDL_HasSSE41", NAPI_SDL_HasSSE41);
  EXPORT_METHOD(exports, "SDL_HasSSE42", NAPI_SDL_HasSSE42);

  EXPORT_METHOD(exports, "SDL_Swap16", NAPI_SDL_Swap16);
  EXPORT_METHOD(exports, "SDL_Swap32", NAPI_SDL_Swap32);
  EXPORT_METHOD(exports, "SDL_Swap64", NAPI_SDL_Swap64);
  EXPORT_METHOD(exports, "SDL_SwapBE16", NAPI_SDL_SwapBE16);
  EXPORT_METHOD(exports, "SDL_SwapBE32", NAPI_SDL_SwapBE32);
  EXPORT_METHOD(exports, "SDL_SwapBE64", NAPI_SDL_SwapBE64);
  EXPORT_METHOD(exports, "SDL_SwapFloat", NAPI_SDL_SwapFloat);
  EXPORT_METHOD(exports, "SDL_SwapFloatBE", NAPI_SDL_SwapFloatBE);
  EXPORT_METHOD(exports, "SDL_SwapFloatLE", NAPI_SDL_SwapFloatLE);
  EXPORT_METHOD(exports, "SDL_SwapLE16", NAPI_SDL_SwapLE16);
  EXPORT_METHOD(exports, "SDL_SwapLE32", NAPI_SDL_SwapLE32);
  EXPORT_METHOD(exports, "SDL_SwapLE64", NAPI_SDL_SwapLE64);

  EXPORT_METHOD(exports, "SDL_MostSignificantBitIndex32", NAPI_SDL_MostSignificantBitIndex32);

  // Power Management Category
  //EXPORT_METHOD(exports, "SDL_GetPowerInfo", NAPI_SDL_GetPowerInfo);


  return exports;
}


NAPI_MODULE(NODE_GYP_MODULE_NAME, Export)
